import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { FC, PropsWithChildren } from "react";

export const MainLayout: FC<PropsWithChildren> = ({ children }) => {
  const { user, isSignedIn, isLoaded: userLoaded } = useUser();
  return (
    <>
      {/* <Head>
			<title>Create T3 App</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
		 </Head> */}
      <main className="w-full">
        {/* <div>
          {!isSignedIn && <SignInButton mode="modal" />}
          {!!isSignedIn && <SignOutButton />}
        </div> */}
        <div className="absolute top-1 left-1 transition-all hover:scale-105">
          {!isSignedIn && <SignInButton mode="modal" />}
          {!!isSignedIn && <SignOutButton />}
        </div>

        <div className=" mx-auto flex h-full min-h-screen w-full flex-col border-x border-gray-600 sm:w-1/2">
          {/* <CrearePostWizard /> */}
          {children}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};
